theme = "doom_acario_dark"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[keys.normal]
C-c = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
C-c = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.select]
C-c = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.soft-wrap]
enable = true
